baseURL = "https://stubbornapp.com"
languageCode = "en-us"
title = "Brutu App"
author = "Pawel Sysiak"
description = "Brutu Timer. Timer that keeps you focus."

publishDir = "docs"
enableEmoji = "true"
paginate = "4"
