baseURL = "https://brutu.app"
languageCode = "en-us"
title = "Brutu Timer"
author = "Max Kant & Pawel Sysiak"
description = "Stay focused or burn your money"

publishDir = "docs"
enableEmoji = "true"
paginate = "4"
